remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Workshop on Data Science for Justice Delivery in India (DSJDI-2022) 
description: (Date - December 19,2022, Tenth International Conference on Big Data Analytics 2022 (BDA 2022), https://bda-2022.github.io/DSJDI-2022/)
